#Requires -Version 5.1

<#
.SYNOPSIS
    test-evidence-analysis.ps1 - Analyze and correlate test evidence files
.DESCRIPTION
    Interprets evidence-*.json and test-evidence-*.json files generated by enhanced-test-bridge.ps1
    Provides comprehensive analysis of test execution history, correlation tracking, and pass/fail patterns
.NOTES
    Purpose: Demonstrate value of evidence artifacts and enable audit trail analysis
    Authority: GuardRails.md + Isolate-Trace-Verify-Loop.md (evidence correlation principle)
#>

[CmdletBinding()]
param(
    [string]$EvidenceDirectory = $PSScriptRoot,
    [switch]$CorrelationOnly,
    [switch]$FailuresOnly,
    [string]$CorrelationId
)

$ErrorActionPreference = 'Stop'

function Write-AnalysisHeader {
    param([string]$Title, [string]$Color = 'Cyan')
    Write-Host "`n" -NoNewline
    Write-Host "=" * 70 -ForegroundColor $Color
    Write-Host "  $Title" -ForegroundColor $Color
    Write-Host "=" * 70 -ForegroundColor $Color
}

function Convert-UnixTimestamp {
    param([string]$DateString)
    try {
        if ($DateString -match '/Date\((\d+)\)/') {
            $milliseconds = [int64]$matches[1]
            [datetime]::new(1970, 1, 1).AddMilliseconds($milliseconds).ToLocalTime()
        } else {
            [datetime]::Parse($DateString)
        }
    } catch {
        $DateString
    }
}

function Analyze-EvidenceFile {
    param([string]$FilePath)
    
    try {
        $Evidence = Get-Content $FilePath | ConvertFrom-Json -ErrorAction Stop
        return $Evidence
    } catch {
        Write-Warning "Failed to parse $($Path | Split-Path -Leaf): $_"
        return $null
    }
}

function Get-EvidenceStatistics {
    param([array]$EvidenceFiles)
    
    $Stats = @{
        TotalFiles      = $EvidenceFiles.Count
        TotalTests      = 0
        PassedTests     = 0
        FailedTests     = 0
        SkippedTests    = 0
        CorrelationIds  = @{}
        Environments    = @{}
        TimeSpan        = $null
    }
    
    foreach ($Evidence in $EvidenceFiles) {
        # Count tests by status
        foreach ($Test in $Evidence.Tests) {
            $Stats.TotalTests++
            switch ($Test.Status.ToUpper()) {
                'PASS'  { $Stats.PassedTests++ }
                'FAIL'  { $Stats.FailedTests++ }
                'SKIP'  { $Stats.SkippedTests++ }
            }
        }
        
        # Track correlation IDs for linking
        if ($Evidence.CorrelationId) {
            if (-not $Stats.CorrelationIds.ContainsKey($Evidence.CorrelationId)) {
                $Stats.CorrelationIds[$Evidence.CorrelationId] = @()
            }
            $Stats.CorrelationIds[$Evidence.CorrelationId] += @{
                File = $Evidence | Get-Member -MemberType NoteProperty | Select-Object -First 1
                Suite = $Evidence.TestSuite
            }
        }
        
        # Track environments
        $EnvKey = "$($Evidence.Environment.PSVersion)|$($Evidence.Environment.PSEdition)"
        if (-not $Stats.Environments.ContainsKey($EnvKey)) {
            $Stats.Environments[$EnvKey] = 0
        }
        $Stats.Environments[$EnvKey]++
    }
    
    return $Stats
}

# Main analysis
Write-AnalysisHeader "TEST EVIDENCE ANALYSIS FRAMEWORK" 'Green'
Write-Host "Scanning for evidence files in: $EvidenceDirectory" -ForegroundColor Gray

# Discover evidence files
$EvidenceFiles = @()
$EvidenceFiles += Get-ChildItem $EvidenceDirectory -Filter 'evidence-*.json' -ErrorAction SilentlyContinue
$EvidenceFiles += Get-ChildItem $EvidenceDirectory -Filter 'test-evidence-*.json' -ErrorAction SilentlyContinue

if ($EvidenceFiles.Count -eq 0) {
    Write-Host "No evidence files found in $EvidenceDirectory" -ForegroundColor Yellow
    exit 0
}

Write-Host "Found $($EvidenceFiles.Count) evidence file(s)" -ForegroundColor Green

# Parse all evidence files
$ParsedEvidence = @()
foreach ($File in $EvidenceFiles) {
    $Parsed = Analyze-EvidenceFile -FilePath $File.FullName
    if ($Parsed) {
        $ParsedEvidence += $Parsed
    }
}

# Filter by correlation ID if specified
if ($CorrelationId) {
    $ParsedEvidence = $ParsedEvidence | Where-Object { $_.CorrelationId -eq $CorrelationId }
    Write-Host "Filtered to $($ParsedEvidence.Count) file(s) matching CorrelationId: $CorrelationId" -ForegroundColor Cyan
}

# Show correlation overview if requested
if ($CorrelationOnly -or $CorrelationId) {
    Write-AnalysisHeader "CORRELATION ID TRACKING" 'Cyan'
    
    $CorrelationMap = @{}
    foreach ($Evidence in $ParsedEvidence) {
        if ($Evidence.CorrelationId) {
            if (-not $CorrelationMap.ContainsKey($Evidence.CorrelationId)) {
                $CorrelationMap[$Evidence.CorrelationId] = @()
            }
            $CorrelationMap[$Evidence.CorrelationId] += @{
                File      = ($EvidenceFiles | Where-Object { $_.Name -match ([regex]::Escape($Evidence.CorrelationId -split '-')[0]) }).Name
                Suite     = $Evidence.TestSuite
                Timestamp = $Evidence.Timestamp.DateTime
                CommitSHA = $Evidence.CommitSHA
            }
        }
    }
    
    foreach ($CorrId in $CorrelationMap.Keys | Sort-Object) {
        Write-Host "`nCorrelationId: $CorrId" -ForegroundColor Yellow
        foreach ($Entry in $CorrelationMap[$CorrId]) {
            Write-Host "  Suite: $($Entry.Suite)" -ForegroundColor Gray
            Write-Host "  Commit: $($Entry.CommitSHA)" -ForegroundColor Gray
            Write-Host "  Time: $($Entry.Timestamp)" -ForegroundColor Gray
        }
    }
}

# Show statistics
Write-AnalysisHeader "TEST EXECUTION STATISTICS" 'Blue'
$Stats = Get-EvidenceStatistics -EvidenceFiles $ParsedEvidence

Write-Host "Total Evidence Files:     $($Stats.TotalFiles)" -ForegroundColor White
Write-Host "Total Tests Executed:     $($Stats.TotalTests)" -ForegroundColor White
Write-Host "  ✓ Passed:               $($Stats.PassedTests)" -ForegroundColor Green
Write-Host "  ✗ Failed:               $($Stats.FailedTests)" -ForegroundColor Red
Write-Host "  ⊘ Skipped:              $($Stats.SkippedTests)" -ForegroundColor Yellow

if ($Stats.TotalTests -gt 0) {
    $PassRate = [math]::Round(($Stats.PassedTests / $Stats.TotalTests) * 100, 2)
    Write-Host "Pass Rate:                $PassRate%" -ForegroundColor $(if ($PassRate -eq 100) { 'Green' } else { 'Yellow' })
}

Write-Host "`nUnique Environments:" -ForegroundColor Cyan
foreach ($Env in $Stats.Environments.Keys | Sort-Object) {
    Write-Host "  $Env ($($Stats.Environments[$Env]) file(s))" -ForegroundColor Gray
}

Write-Host "`nUnique Correlation IDs:   $($Stats.CorrelationIds.Keys.Count)" -ForegroundColor Cyan

# Show detailed test results
Write-AnalysisHeader "DETAILED TEST RESULTS" 'Magenta'

foreach ($Evidence in $ParsedEvidence | Sort-Object { $_.Timestamp.DateTime } -Descending) {
    $TimeStamp = $Evidence.Timestamp.DateTime
    Write-Host "`nTestSuite: $($Evidence.TestSuite) | Commit: $($Evidence.CommitSHA)" -ForegroundColor Cyan
    Write-Host "Time: $TimeStamp | CorrelationId: $($Evidence.CorrelationId)" -ForegroundColor Gray
    Write-Host "Environment: PS $($Evidence.Environment.PSVersion) ($($Evidence.Environment.PSEdition))" -ForegroundColor Gray
    
    foreach ($Test in $Evidence.Tests) {
        $StatusColor = switch ($Test.Status.ToUpper()) {
            'PASS' { 'Green' }
            'FAIL' { 'Red' }
            'SKIP' { 'Yellow' }
            default { 'White' }
        }
        
        $StatusSymbol = switch ($Test.Status.ToUpper()) {
            'PASS' { '✓' }
            'FAIL' { '✗' }
            'SKIP' { '⊘' }
            default { '?' }
        }
        
        # Skip passing tests unless explicitly requested
        if ($FailuresOnly -and $Test.Status.ToUpper() -eq 'PASS') {
            continue
        }
        
        Write-Host "  $StatusSymbol $($Test.Name)" -ForegroundColor $StatusColor
        Write-Host "    Evidence: $($Test.Evidence)" -ForegroundColor Gray
        Write-Host "    Time: $($Test.Timestamp.DateTime)" -ForegroundColor Gray
    }
}

# Show failure summary
if ($Stats.FailedTests -gt 0) {
    Write-AnalysisHeader "FAILURE PATTERNS" 'Red'
    
    $FailureMap = @{}
    foreach ($Evidence in $ParsedEvidence) {
        foreach ($Test in $Evidence.Tests) {
            if ($Test.Status.ToUpper() -eq 'FAIL') {
                if (-not $FailureMap.ContainsKey($Test.Name)) {
                    $FailureMap[$Test.Name] = @()
                }
                $FailureMap[$Test.Name] += @{
                    Evidence = $Test.Evidence
                    Time     = $Test.Timestamp.DateTime
                    Suite    = $Evidence.TestSuite
                }
            }
        }
    }
    
    foreach ($TestName in $FailureMap.Keys | Sort-Object) {
        Write-Host "`n$TestName" -ForegroundColor Yellow
        $FailureMap[$TestName] | Sort-Object Time -Descending | ForEach-Object {
            Write-Host "  Suite: $($_.Suite) | Time: $($_.Time)" -ForegroundColor Gray
            Write-Host "  Error: $($_.Evidence)" -ForegroundColor Red
        }
    }
}

# Summary
Write-AnalysisHeader "EVIDENCE INTEGRATION SUMMARY" 'Green'
Write-Host "Purpose: Test artifacts are sequential evidence of successful validation" -ForegroundColor Gray
Write-Host "Usage: CorrelationId links evidence across multiple test runs" -ForegroundColor Gray
Write-Host "Gate Policy: Evidence files excluded from untracked file violations" -ForegroundColor Gray
Write-Host "Retention: All evidence indexed for audit trail reconstruction" -ForegroundColor Gray
Write-Host "`nEvidence files demonstrate constitutional compliance through:" -ForegroundColor White
Write-Host "  1. TestSuite identification and reproducibility" -ForegroundColor Gray
Write-Host "  2. Timestamp correlation for sequencing verification" -ForegroundColor Gray
Write-Host "  3. CommitSHA linking to specific code versions" -ForegroundColor Gray
Write-Host "  4. Environment tracking (PS version, OS platform, etc.)" -ForegroundColor Gray
Write-Host "  5. Test result audit trail with pass/fail evidence" -ForegroundColor Gray
